// @ts-check
import { createHash } from 'node:crypto';
import react from '@astrojs/react';
import sitemap from '@astrojs/sitemap';
import tailwindcss from '@tailwindcss/vite';
import { defineConfig } from 'astro/config';
import { SETTINGS_STORAGE_KEY } from './src/constants/storage.ts';
import {
  languageRedirectScript,
  notFoundLanguageScript,
  themeScript,
} from './src/utils/inline-scripts/inline-scripts.ts';
import { DEFAULT_LOCALE, LOCALES } from './src/utils/locale/locale.ts';

// Local builds read .env too (CI passes the variables directly).
try {
  process.loadEnvFile();
} catch {
  // No .env file.
}

// Public origin and path of the deployed site: canonical URLs, hreflang, sitemap and Open Graph.
// GitHub Pages serves this project under https://inzumer.github.io/milimon.
const site = process.env.SITE_URL ?? 'https://inzumer.github.io';
const base = process.env.BASE_PATH || '/';

/** @param {string | undefined} url */
const origin = (url) => {
  try {
    return url ? new URL(url).origin : null;
  } catch {
    return null;
  }
};
const apiOrigin = origin(process.env.PUBLIC_API_URL);

// Inline scripts that must run before any module (theme without flash, root language redirect,
// 404 language):
// the page renders these exact strings, so their hashes can be allowed without 'unsafe-inline'.
/**
 * @param {string} text
 * @returns {`sha256-${string}`}
 */
const sha256 = (text) => `sha256-${createHash('sha256').update(text).digest('base64')}`;
const inlineScriptHashes = [
  sha256(themeScript(SETTINGS_STORAGE_KEY)),
  sha256(
    languageRedirectScript({
      storageKey: SETTINGS_STORAGE_KEY,
      locales: LOCALES,
      fallbackLocale: DEFAULT_LOCALE,
      base: base.replace(/\/+$/, ''),
    }),
  ),
  sha256(notFoundLanguageScript({ locales: LOCALES, base: base.replace(/\/+$/, '') })),
];

// Content-Security-Policy (meta tag with hashes of our own scripts and styles, generated by Astro).
// Tokens live in localStorage, so blocking injected scripts matters. Only the services we use are
// allowed: the accounts API, Google sign-in, Facebook Login and Google Tag Manager / Analytics.
/** @type {`connect-src ${string}`} */
const connectSrc = /** @type {`connect-src ${string}`} */ (
  [
    "connect-src 'self'",
    apiOrigin,
    'https://accounts.google.com',
    'https://graph.facebook.com',
    'https://*.facebook.com',
    'https://www.googletagmanager.com',
    'https://*.google-analytics.com',
    'https://*.analytics.google.com',
  ]
    .filter(Boolean)
    .join(' ')
);

/** @type {Exclude<NonNullable<NonNullable<import('astro').AstroUserConfig['security']>['csp']>, boolean>} */
const csp = {
  directives: [
    "default-src 'self'",
    connectSrc,
    "img-src 'self' data: https://*.googleusercontent.com https://*.fbcdn.net https://platform-lookaside.fbsbx.com https://www.googletagmanager.com https://*.google-analytics.com",
    'frame-src https://accounts.google.com https://*.facebook.com https://www.googletagmanager.com',
    "font-src 'self'",
    "object-src 'none'",
    "base-uri 'self'",
    "form-action 'self'",
  ],
  scriptDirective: {
    resources: [
      "'self'",
      'https://accounts.google.com',
      'https://connect.facebook.net',
      'https://www.googletagmanager.com',
    ],
    hashes: inlineScriptHashes,
  },
  // Google's sign-in button injects inline styles (a <style> element and style attributes).
  // Styles can't run code or read storage, so they are allowed inline; scripts stay hash-only.
  styleDirective: {
    resources: [
      "'self'",
      'https://accounts.google.com',
      { resource: "'self'", kind: 'element' },
      { resource: "'unsafe-inline'", kind: 'element' },
      { resource: 'https://accounts.google.com', kind: 'element' },
      { resource: "'unsafe-inline'", kind: 'attribute' },
    ],
  },
};

// https://docs.astro.build/en/reference/configuration-reference/
export default defineConfig({
  site,
  base,
  output: 'static',
  trailingSlash: 'never',
  // One HTML file per page (es/login.html): GitHub Pages serves /es/login directly, without the
  // redirect to /es/login/ that folder-style output causes.
  build: { format: 'file' },
  security: { csp },
  integrations: [
    react(),
    sitemap({
      i18n: { defaultLocale: 'es', locales: { es: 'es', en: 'en' } },
      // The root only redirects by language, 404 isn't a real page and the account, login and
      // history pages are personal.
      filter: (page) => {
        const { pathname } = new URL(page);
        const route = pathname.slice(base.replace(/\/+$/, '').length) || '/';
        return (
          route !== '/' &&
          !route.includes('404') &&
          !/\/(account|history|login|recipes)$/.test(route)
        );
      },
    }),
  ],
  i18n: {
    locales: ['es', 'en'],
    defaultLocale: 'es',
    routing: {
      prefixDefaultLocale: true,
      redirectToDefaultLocale: false,
    },
  },
  vite: {
    plugins: [tailwindcss()],
  },
});
